language: dart
services:
    - docker
before_install:
    - docker pull cirrusci/flutter
    - docker run -d --name flutter --mount src="$(pwd)",target=/workspace,type=bind cirrusci/flutter /bin/sh -c "sleep infinity"
install:
    - docker exec -it flutter /bin/sh -c "cd /workspace && flutter packages get"
script:
    - docker exec -it flutter /bin/sh -c "cd /workspace && flutter analyze"
    - docker exec -it flutter /bin/sh -c "cd /workspace && flutter test"
