name: deep_kitten
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  image_picker: ^0.6.3
  dio: ^3.0.8
  image: 2.1.4
  video_player: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  flutter_launcher_icons: "^0.7.4"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
   - assets/videos/

flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#ff9bdfff"
