version: '3'
services:
  dev:
    command: sleep infinity
    build:
      context: .
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/cirrus/.ssh
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
